---
title: "review paper sunburst plots"
author: "Emma Johnson"
date: "2025-11-06"
output: html_document
---

Script from Juliet Wong - RCN-ECS Fluctuating Selection, empirical studies figures

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install and load packages
```{r}
library(plotly)
library(readr)
library(UpSetR)
library(here)
library(processx)
library(webshot)
library(htmlwidgets)
```

```{r save_sunburst_pdf, message=FALSE, warning=FALSE}
phyla <- read_csv("/Users/emmajohnson/Desktop/Wong Lab/Review Paper/EmGePt_LitReview/Data/sunburstplot_phyla.csv")

phyla_fig <- plot_ly(phyla, ids = ~ids, labels = ~labels, 
                     parents = ~parents, values= ~values, 
                     type = 'sunburst', branchvalues = 'total',
                     insidetextorientation='tangential',
                     width = 500, height = 500,
                     marker = list(colors = ~colors),
                     color = I('#000000'))

htmlwidgets::saveWidget(phyla_fig, "phyla_sunburst.html")
webshot::webshot("phyla_sunburst.html", "phyla_sunburst.pdf",
                 vwidth = 800, vheight = 800, delay = 1)

phyla_fig
```

```{r save_sunburst_pdf, message=FALSE, warning=FALSE}
stressor <- read_csv("/Users/emmajohnson/Desktop/Wong Lab/Review Paper/EmGePt_LitReview/Data/sunburstplot_stressor.csv")

stressor_fig <- plot_ly(stressor, ids = ~ids, labels = ~labels, 
                        parents = ~parents, values= ~values, 
                        type = 'sunburst', branchvalues = 'total',
                        insidetextorientation='tangential',
                        width = 500, height = 500,
                        marker = list(colors = ~colors),
                        color = I('#000000'))

htmlwidgets::saveWidget(stressor_fig, "stressor_sunburst.html")
webshot::webshot("stressor_sunburst.html", "stressor_sunburst.pdf",
                 vwidth = 800, vheight = 800, delay = 1)

stressor_fig

# Other:
#   HABs 4
# 	Injury 3
# 	Upwelling 3
# 	Avestiation 2
# 	Multiple 2
# 	Radiation 2
# 	Desiccation 1
# 	Light availability	1
```


```{r save_sunburst_pdf, message=FALSE, warning=FALSE}
epimod <- read_csv("/Users/emmajohnson/Desktop/Wong Lab/Review Paper/EmGePt_LitReview/Data/sunburstplot_epimod.csv")

epi_mod_fig <- plot_ly(epimod,
                       ids = ~ids,
                       labels = ~labels,
                       parents = ~parents,
                       values = ~values,
                       type = 'sunburst',
                       branchvalues = 'total',
                       insidetextorientation = 'tangential',
                       marker = list(colors = ~colors),
                       color = I('#000000'))

htmlwidgets::saveWidget(epi_mod_fig, "epimod_sunburst.html")
webshot::webshot("epimod_sunburst.html", "epimod_sunburst.pdf",
                 vwidth = 800, vheight = 800, delay = 1)
epi_mod_fig
```

```{r save_sunburst_pdf, message=FALSE, warning=FALSE}
transgen <- read_csv("/Users/emmajohnson/Desktop/Wong Lab/Review Paper/EmGePt_LitReview/Data/sunburstplot_transgenerational.csv")

transgen_fig <- plot_ly(transgen, ids = ~ids, labels = ~labels, 
                       parents = ~parents, values= ~values, 
                       type = 'sunburst', branchvalues = 'total',
                       insidetextorientation='tangential',
                       width = 500, height = 500,
                       marker = list(colors = ~colors),
                       color = I('#000000'))

htmlwidgets::saveWidget(transgen_fig, "transgen_sunburst.html")
webshot::webshot("transgen_sunburst.html", "transgen_sunburst.pdf",
                 vwidth = 800, vheight = 800, delay = 1)

transgen_fig
```















